### ISSUE TITLE
Update text on Firefox Voice campaign page

### ISSUE THREAD

**Issue by harraton** [mozilla/firefox_voice_community#17]
Update text to the following:

Firefox Voice is an experiment from Mozilla that lets you browse and get more done with your voice—faster than ever. We are looking for fearless early adopters who are willing to test the new add-on and give us feedback before the major public release.

**Comment by harraton** [comment]
This URL: https://events.mozilla.org/firefoxvoicecampaign

**Comment by harraton** [comment]
@MichaelKohler Are you the right person to help with this?

**Comment by couci** [comment]
thanks @harraton for the suggestions, @awallin are you ok with this change?

**Comment by awallin** [comment]
Yes, we need to highlight the experimental nature of the product.

**Comment by couci** [comment]
changed
