### ISSUE TITLE
Additional updates needed for Firefox Voice Campaign page

### ISSUE THREAD

**Issue by harraton** [mozilla/firefox_voice_community#18]
Update button text to "Get started."

Once you click the button, update "RSVP" to "Sign up"

Fix the font size for the "Just a few things you can do" section to match the font size of the section above it.

**Comment by couci** [comment]
- on "Get started" I am ok with the change @awallin is that ok?
- RSVP can not be changed, it's a form limitation
- Font size can not be changed, it is supposed to match the titles thus this is the reason we have it like that

**Comment by awallin** [comment]
I'm good with 'Get started'

**Comment by couci** [comment]
changed

**Comment by awallin** [comment]
@couci I'm seeing weird double text for the "Get started" button.

<img width="659" alt="Screen Shot 2019-12-06 at 8 31 51 AM" src="https://user-images.githubusercontent.com/428245/70339104-0f5dde80-1803-11ea-8a1f-5a62bfdaf6e2.png">

**Comment by harraton** [comment]
The Get Started button is broken. Instead of popping up the RSVP, it goes to a blank splashthat.com page.

**Comment by couci** [comment]
this has been fixed
