### ISSUE TITLE
Firefox Campaign page: Add a link to where to file a bug

### ISSUE THREAD

**Issue by harraton** [mozilla/firefox_voice_community#19]
Links should be added about where to file a bug.

Update text in the "How to Help" section. 

 "File any bug you might find in [Github](https://github.com/mozilla/firefox_voice_community/issues/new) or on our [feedback page.](https://firefox-voice-feedback.herokuapp.com)"

Add a link to "How to File a Bug or Feedback Request." 
https://firefox-voice-feedback.herokuapp.com

**Comment by couci** [comment]
Link added. I would prefer to prompt people only on the bug/feedback page instead of our github
