### ISSUE TITLE
[BUG] Add links to Github and Bug/Feature Request form in the Campaign email

### ISSUE THREAD

**Issue by harraton** [mozilla/firefox_voice_community#21]
In the email that is received once you RSVP, please add links to Github and the feedback form:

"You may submit an [issue on GitHub](https://github.com/mozilla/firefox_voice_community/issues/new)), fill out our [feedback form](https://firefox-voice-feedback.herokuapp.com/), ..."

**Comment by awallin** [comment]
@harraton Attached is the mockup I provided @couci. I think we should limit the number of links in the email as it will get confusing what to click to install. Feedback and GitHub details are available in other locations on the campaign page and in product. Let's focus this email on installation.

![install-email](https://user-images.githubusercontent.com/428245/70357335-798a7980-182b-11ea-98e5-b64c4c179cf4.jpg)

**Comment by harraton** [comment]
Got it. 

The works "Privacy FAQ" should be removed then from the email. 

<img width="468" alt="Screen Shot 2019-12-06 at 10 50 00 PM" src="https://user-images.githubusercontent.com/5941526/70370332-dfeab880-187a-11ea-9e77-8eea863137b5.png">

**Comment by couci** [comment]
This is now changed, I took out the email of the team and added just the feedback form. In that way, we keep feedback/bugs in one place. Here is the screenshot of what you are receiving now:
<img width="518" alt="Screenshot 2019-12-09 at 15 48 27" src="https://user-images.githubusercontent.com/7702955/70445178-6f6eb200-1a9b-11ea-9390-422b7238d6b4.png">

**Comment by awallin** [comment]
Looks good!

**Comment by awallin** [comment]
Email is good and has been sent!
