### ISSUE TITLE
Different feedback possibilities given at the end of addon installation instruction. 

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/firefox_voice_community#23]
Hi,
The document that give instruction on how to install the addon gives three ways for people to report issues with installation. It might be better to direct them to the feedback form. The link to the document is here: https://docs.google.com/document/d/1nTyIw4G1yWnxlTmJ-Nvs9OIDntAIYmRPMLKVJZ9TxkI/edit . The part that should be changed is at then end of the document.

**Comment by couci** [comment]
@harraton We should only point them to the feedback/bug form: https://firefox-voice-feedback.herokuapp.com/

The rest can be confusing, could you remove them?

**Comment by couci** [comment]
this is now fixed
