### ISSUE TITLE
Incorrect Location for Resturant Search [BUG]

### ISSUE THREAD

**Issue by VickyEWood** [mozilla/firefox_voice_community#234]
**Firefox Version**

72.0.1 (64-bit)

**What device are you using?**

MacBook Pro (15-inch, Mid 2009)

**Where are you currently based**

Canada

**Issue Type**

- [X] Doesn't behave as expected
- [ ] Didn't understand me
- [ ] Performance issue or slow
- [ ] Other

**Issue Description**
Steps to reproduce the behaviour:
1. Click on Voice Icon in Firefox browser
2. Say "what's the nearest restaurant?"
3. See incorrect location results on the map

**What were you hoping/expecting Firefox Voice to do?**

I was hoping that Firefox Voice would return a results page showing a list of restaurants near my current location which is: Bowen Island, BC, Canada

**Actual behaviour**

Firefox Voice returned a results page for downtown Vancouver, BC.

**Screenshots**

![Screen Shot 2020-01-16 at 4 50 32 PM](https://user-images.githubusercontent.com/59984406/72575505-80bc9280-3881-11ea-95c7-33e8846d329f.png)

**Comment by awallin** [comment]
Thanks for the report @VickyEWood. For this request Firefox Voice uses on Google to operate a search. I assume based on your IP address Google has you in Vancouver thus the results. Unfortunately, we won't be able to improve the location results with Firefox Voice.
