### ISSUE TITLE
[FEATURE] Support Firefox on Android (either Fennec or Fenix)

### ISSUE THREAD

**Issue by madb1lly** [mozilla/firefox_voice_community#250]
Hi,
Please can you make the add-on work with Firefox on Android, either Fennec or Fenix? I would be able to test it more then.
Thanks :)

**Comment by awallin** [comment]
@madb1lly Thanks for the request. We're exploring the possibilities with Android. I can't provide a  timeline but it's a high priority on our roadmap.

**Comment by madb1lly** [comment]
Hi @awallin why is this a duplicate request? I can't find another previous issue with the same scope.
Cheers 🙂

**Comment by awallin** [comment]
Sorry @madb1lly forgot to include this link. We've got a milestone in progress where we're working on producing a demo of Firefox Voice working in Android.

https://github.com/mozilla/firefox-voice/milestone/12
