### ISSUE TITLE
[FEATURE] Incorporate into mobile versions

### ISSUE THREAD

**Issue by dpbaril** [mozilla/firefox_voice_community#255]
I am surprised this hasn't been identified before. I searched through the list of outstanding issues and don't see it anywhere. Perhaps it's already in a roadmap that I am not aware of. In any case it seems abundantly clear to me that it would make sense to have Firefox voice included with the mobile browsers as well as with desktop version.

**Comment by madb1lly** [comment]
Hi @dpbaril it has been raised before #250 but was closed and marked duplicate.
Cheers 🙂

**Comment by awallin** [comment]
Yes, we're experimenting with what's needed to enable Firefox Voice in Android. Follow along here.

https://github.com/mozilla/firefox-voice/milestone/12
