### ISSUE TITLE
[FEATURE] Github login for bug form

### ISSUE THREAD

**Issue by Djfe** [mozilla/firefox_voice_community#50]
Would be nice if I could log into the form like it was possible for the webcompat sprint so it doesn't just @ me with my username but creates the issue on github in my name instead :)
example: https://github.com/webcompat/web-bugs/issues/27798

That would allow me to use github's issue system for filtering by bug author etc.

**Comment by MichaelKohler** [comment]
Indeed, that would be nice. Too late for this campaign though. I will keep this in mind for future uses of the same code base, maybe the next one, maybe the one after it. 

Thanks for filing!
