### ISSUE TITLE
Autofill Firefox information

### ISSUE THREAD

**Issue by couci** [mozilla/firefox_voice_community#8]
Could we autofill the Firefox information in the form?

**Comment by MichaelKohler** [comment]
this would assume that the user is using the Firefox instance to report that has the problem. What if I report issues on the laptop, but the issue happened on my phone?

**Comment by awallin** [comment]
Auto-fill would be great. If we can't detect the version (e.g. using a different browser to fill out the form or on a mobile phone) maybe the filed could simply not auto-fill?

At this time Firefox Voice is not available on a mobile phone so it's unlikely participants will fill out feedback on their phones.
