### ISSUE TITLE
Drop down for the countries

### ISSUE THREAD

**Issue by couci** [mozilla/firefox_voice_community#9]
Having a dropdown with all the countries so we ensure the user won't do mistakes

**Comment by MichaelKohler** [comment]
What do you classify as mistakes? I try to avoid hardcoded country lists as much as possible, as there are a lot of differences on what is a country and its name depending on who you ask.

**Comment by MichaelKohler** [comment]
e.g. would it be an issue if somebody writes "Grmany" instead of "Germany"? If somebody writes a city instead of a country because they misunderstood?

**Comment by awallin** [comment]
For clarity around what geographic information we're looking for and easier user input a drop down (or even better type ahead match) would be ideal. It'll also help if we get a lot of feedback making the job of sorting/interpreting data easier on the backend.

The concern around missing countries from the list or different names/interpretations is legitimate but in this case I believe the trade off for easier input and backend sythesis is worth it.

**Comment by MichaelKohler** [comment]
> the job of sorting/interpreting data easier on the backend

Then maybe GitHub issues is not the best backend ;)
